### ISSUE TITLE
Self Hosted: Adding Webauthn FIDO2 does not work. 

### ISSUE THREAD

**Issue by joshuabeny1999** [bitwarden/server#1787]
### Steps To Reproduce

1. Go to Setting - 2FA
2. Manage next to Webauthn
3. Add Security Key via Add
4. Click on Save

### Expected Result

That I could add the Yubikey to activate 2FA login

### Actual Result

I can not save the newly Added Security Key to use for Bitwarden. I have premium over the Family Organisation which is added. Also happens when i try to add a Yubikey via the Yubico Method. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/55023662/147559076-97137ca5-058b-4725-b7d8-61d0af958d11.png)
![image](https://user-images.githubusercontent.com/55023662/147559115-021d491f-71f1-4762-bf6a-b843062d13b8.png)

### Additional Context

I use Bitwarden behind an Nginx-Proxy. So I have added following Docker-Compose Overwrite:
```
version: '3'

services:
  nginx:
      environment:
        VIRTUAL_PORT: 8080
        VIRTUAL_HOST: vault.joshuah.ch
        LETSENCRYPT_HOST: vault.joshuah.ch
        LETSENCRYPT_EMAIL: joshua@joshuah.ch

networks:
  default:
    external:
      name: nginx-proxy
```

### Build Version

1.43.5, Web 2.25.0

### Environment

Self-Hosted

### Environment Details

- Windows 10, Webvault in Microsoft Edge Browser
