### ISSUE TITLE
Unable to update: error decoding 'Ports': Invalid ip address: 80

### ISSUE THREAD

**Issue by FieldofClay** [bitwarden/server#1800]
### Steps To Reproduce

1. run './bitwarden.sh update'

### Expected Result

Bitwarden updates.

### Actual Result

```
% ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed5707e
Docker Compose version 2.2.3

1 error(s) decoding:

* error decoding 'Ports': Invalid ip address: 80
```

### Additional Context

I have tried a './bitwarden.sh rebuild', however that did not resolve anything.

### Build Version

2.22.3

### Environment

Self-Hosted

### Environment Details

OS: Arch Linux
Environment: Docker
bitwarden.sh: 1.45.2
Docker: 20.10.12, build e91ed5707e
Docker Compose: 2.2.3

**Comment by Hinton** [comment]
Hi @FieldofClay,

It sounds like something is wrong in your docker-compose.yml file. I found a similar bug report at https://github.com/docker/compose-cli/issues/1652 which suggest there might be a duplicated port entry somewhere.

**Comment by FieldofClay** [comment]
Unfortunately that doesn't appear to be the issue. I couldn't find any duplicate entries in my docker-compose.yml, but removed it and generated another one with "./bitwarden.sh updateconf" and still had the same issue.
I've also gone through my config.yml in search of duplicate port lines, but I only have one each of 'http_port' and 'https_port'.

**Comment by Hinton** [comment]
Could you post a copy of your `docker-compose.yml` file?

**Comment by FieldofClay** [comment]
I've got the generated `docker-compose.yml` below, as well as the core of the `config.yml` that I'm using.
```
version: '3'

services:
  mssql:
    image: bitwarden/mssql:1.45.2
    container_name: bitwarden-mssql
    restart: always
    stop_grace_period: 60s
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../logs/mssql:/var/opt/mssql/log
      - ../mssql/backups:/etc/bitwarden/mssql/backups
    env_file:
      - mssql.env
      - ../env/uid.env
      - ../env/mssql.override.env

  web:
    image: bitwarden/web:2.25.0
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web
    env_file:
      - global.env
      - ../env/uid.env

  attachments:
    image: bitwarden/attachments:1.45.2
    container_name: bitwarden-attachments
    restart: always
    volumes:
      - ../core/attachments:/etc/bitwarden/core/attachments
    env_file:
      - global.env
      - ../env/uid.env

  api:
    image: bitwarden/api:1.45.2
    container_name: bitwarden-api
    restart: always
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/api:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  identity:
    image: bitwarden/identity:1.45.2
    container_name: bitwarden-identity
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/identity:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  sso:
    image: bitwarden/sso:1.45.2
    container_name: bitwarden-sso
    restart: always
    volumes:
      - ../identity:/etc/bitwarden/identity
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/sso:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  admin:
    image: bitwarden/admin:1.45.2
    container_name: bitwarden-admin
    restart: always
    depends_on:
      - mssql
    volumes:
      - ../core:/etc/bitwarden/core
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/admin:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  icons:
    image: bitwarden/icons:1.45.2
    container_name: bitwarden-icons
    restart: always
    volumes:
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/icons:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
    networks:
      - default
      - public

  notifications:
    image: bitwarden/notifications:1.45.2
    container_name: bitwarden-notifications
    restart: always
    volumes:
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/notifications:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  events:
    image: bitwarden/events:1.45.2
    container_name: bitwarden-events
    restart: always
    volumes:
      - ../ca-certificates:/etc/bitwarden/ca-certificates
      - ../logs/events:/etc/bitwarden/logs
    env_file:
      - global.env
      - ../env/uid.env
      - ../env/global.override.env
    networks:
      - default
      - public

  nginx:
    image: bitwarden/nginx:1.45.2
    container_name: bitwarden-nginx
    restart: always
    depends_on:
      - web
      - admin
      - api
      - identity
    ports:
      - '80:8085:8080'
      - '443:8443:8443'
    volumes:
      - ../nginx:/etc/bitwarden/nginx
      - ../letsencrypt:/etc/letsencrypt
      - ../ssl:/etc/ssl
      - ../logs/nginx:/var/log/nginx
    env_file:
      - ../env/uid.env
    networks:
      - default
      - public


networks:
  default:
    internal: true
  public:
    internal: false
```
`config.yml`:
```
url: https://bitwarden.mydomain.com
generate_compose_config: true
generate_nginx_config: true
http_port: 80:8085
https_port: 443:8443
compose_version:
captcha: false
ssl: true
ssl_versions:
ssl_ciphersuites:
ssl_managed_lets_encrypt: false
ssl_certificate_path: /path/to/bitwarden.mydomain.com/certificate.crt
ssl_key_path: /path/to/bitwarden.mydomain.com/private.key
ssl_ca_path:
ssl_diffie_hellman_path:
nginx_header_content_security_policy: "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://haveibeenpwned.com https://www.gravatar.com; child-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-src 'self' https://*.duosecurity.com https://*.duofederal.com; connect-src 'self' wss://{0} https://api.pwnedpasswords.com https://twofactorauth.org; object-src 'self' blob:;"
push_notifications: true
database_docker_volume: false
real_ips:
enable_key_connector: false
```
