### ISSUE TITLE
BitWarden Self-Hosted SSO Not Working

### ISSUE THREAD

**Issue by Rezkmike** [bitwarden/server#2491]
### Steps To Reproduce

I deploy a self-hosted Bitwarden servers and try to enable SSO for user authentication.  

Step to reproduce  : 

1. Click login via "Enterprise Single-Sign on "

![image](https://user-images.githubusercontent.com/48907062/206995816-008cbb7b-bab5-4558-be1e-d96bc0c82474.png)

2. Enter organization and Click on "Log In" button

![image](https://user-images.githubusercontent.com/48907062/206995949-cbac93d5-acd3-4638-96c1-48832346002d.png)

3. Error show up

![image](https://user-images.githubusercontent.com/48907062/206995996-57bb2c70-ab67-49e2-b47f-ec35e1cc87d6.png)

### Expected Result

User may able to login via SSO & Organization Identifier. 

### Actual Result

User not able to login via SSO and keep receiving this error 

```bash
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/48907062/206995996-57bb2c70-ab67-49e2-b47f-ec35e1cc87d6.png)

### Build Version

Docker Image : bitwarden/*:2022.10.0

### Environment

Self-Hosted

### Environment Details

- Environment : K8S

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Rezkmike** [comment]
Error from Nginx Proxy 

![image](https://user-images.githubusercontent.com/48907062/207013621-074c9d98-c54c-4edf-b212-36296a58c1af.png)

**Comment by Rezkmike** [comment]
Error from Nginx container

![image](https://user-images.githubusercontent.com/48907062/207013778-f2384c12-453a-4162-83e7-cc8856596ee1.png)

**Comment by Rezkmike** [comment]
Now im getting this error after added ```globalSettings__baseServiceUri__internalSso``` env variable

![image](https://user-images.githubusercontent.com/48907062/207016837-a8d07b9b-def5-43d7-8cf3-222a56f8e638.png)

**Comment by kspearrin** [comment]
Is this using the unified container? Did you enable the SSO service from env vars?

**Comment by Rezkmike** [comment]
I deployed on docker generated from the bash script provided and then I transferred to Kubernetes cluster. Btw its working now. 

Solution :  
1. Need to add few ENV variables
2. Tweak a bit OIDC setting, the Official documentation showing setting not accurate. 
3. Restart Kubernetes deployment

Now its working fine.

**Comment by ErikHumphrey** [comment]
@Rezkmike What OIDC settings did you tweak? Can you post your whole OIDC configuration with secrets omitted?

**Comment by Rezkmike** [comment]
Hi @kspearrin , yaa sure.

1. OIDC setting

```bash
Metadata Address: https://XXXX.okta.com/.well-known/openid-configuration
```

2. Kubernetes Secret Env 

```yaml
apiVersion: bitnami.com/v1alpha1
kind: Secret
metadata:
  name: bw-secret
  namespace: bw
spec:
  encryptedData: 
    globalSettings__baseServiceUri__vault: XXX
    globalSettings__identityServer__certificatePassword: XXX
    globalSettings__internalIdentityKey: XXX
    globalSettings__oidcIdentityClientKey: XXX
    globalSettings__duo__aKey: XXX
    globalSettings__installation__id: XXX
    globalSettings__installation__key: XXX
    globalSettings__yubico__clientId: XXX
    globalSettings__yubico__key: XXX
    globalSettings__mail__smtp__host: XXX
    globalSettings__mail__smtp__port: XXX
    globalSettings__mail__smtp__username: XXX
    globalSettings__mail__smtp__password: XXX
    globalSettings__mail__smtp__ssl: XXX
    globalSettings__mail__replyToEmail: XXX
    globalSettings__disableUserRegistration: XXX
    globalSettings__hibpApiKey: XXX
    globalSettings__pushRelayBaseUri: XXX
    globalSettings__selfHosted: XXX
    ASPNETCORE_ENVIRONMENT: XXX
    adminSettings__admins: XXX
    SA_PASSWORD: XXX
    LOCAL_UID: XXX
    LOCAL_GID: XXX
    ACCEPT_EULA: XXX
    MSSQL_PID: XXX
    globalSettings__baseServiceUri__internalNotifications: XXX
    globalSettings__baseServiceUri__internalAdmin: XXX
    globalSettings__baseServiceUri__internalIdentity: XXX
    globalSettings__baseServiceUri__internalApi: XXX
    globalSettings__baseServiceUri__internalVault: XXX
    globalSettings__baseServiceUri__internalSso: XXX
    globalSettings__sqlServer__connectionString: XXX
```
