### ISSUE TITLE
Cannot send emails using docker run

### ISSUE THREAD

**Issue by GieltjE** [bitwarden/server#2533]
### Steps To Reproduce

1: install using docker compose up, verify that /admin sends the email correctly
2: docker rm bitwarden-bitwarden-1 (gets a funny name using docker compose up, this is the only discernable difference)
3: start it using the alternative method (e.g. docker run -d --name bitwarden -v C:\Users\MichielHazelhof\Desktop\bitwarden\bwdata:/etc/bitwarden -p 80:8080  --env-file settings.env bitwarden/self-host:beta)
4: attempt to get the email from /admin

### Expected Result

Emails should always arive and if they don't a log should be generated

### Actual Result

No email is sent (no logs on the mailserver) and no local failure log is generated

### Githash Version

455d62e8-dirty

### Environment Details

- OS: Win 11 insider
- Env: Docker
- Hardware: 3700X 64GB ram

### Database Image

Mariadb: 10.10.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Apologies if this is what you mean by "local failure log" but do you have any error messages in `/var/log/bitwarden/admin.log`?

**Comment by GieltjE** [comment]
The admin.log doesn't display anything, the call to http://localhost/admin/login is much, much faster too.

**Comment by GieltjE** [comment]
On a side note, the example docker-compose.yaml (https://github.com/bitwarden/server/blob/master/docker-unified/docker-compose.yml) contains a mount path for the logs.

The docker run example (https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-run) does not.

**Comment by kspearrin** [comment]
Did you configure a mail server in your env vars?

**Comment by GieltjE** [comment]
Yes, using "docker compose up" with the same settings.env file works just fine, docker even reports the same env variables.

**Comment by kspearrin** [comment]
There should be no difference as long as you are using the correct command. Are you sure you don't need to specify a more absolute path to the settings.env?

**Comment by GieltjE** [comment]
```
docker run -d --name bitwarden -v C:\Users\MichielHazelhof\Desktop\bitwarden\logs:/var/log/bitwarden -v C:\Users\MichielHazelhof\Desktop\bitwarden\bwdata:/etc/bitwarden -p 80:8080 --env-file C:\Users\MichielHazelhof\Desktop\bitwarden\settings.env bitwarden/self-host:beta
```

docker-compose.yml
```
version: "3.8"

services:
  bitwarden:
    env_file:
      - C:\Users\MichielHazelhof\Desktop\bitwarden\settings.env
    image: bitwarden/self-host:beta
    restart: always
    ports:
      - "80:8080"
    volumes:
      - C:\Users\MichielHazelhof\Desktop\bitwarden\bwdata:/etc/bitwarden
      - C:\Users\MichielHazelhof\Desktop\bitwarden\logs:/var/log/bitwarden

volumes:
  bitwarden:
  data:
```

The first will absuletely not send emails, the second one does so without a hitch.
