### ISSUE TITLE
502 Bad Gateway nginx behind traefik 2 reverse proxy

### ISSUE THREAD

**Issue by iamspido** [bitwarden/server#2652]
### Steps To Reproduce

1. run bitwarden.sh install
2. edit config.yml to url with https
3. run bitwarden.sh rebuild
4. edit global.override.env to globalSettings__baseServiceUri__vault with https and setup smtp settings and add adminSettings__admins
5. add docker-compose.override.yml
```                                                                      
version: '3'
services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.domain.de`)"
      - "traefik.http.routers.bitwarden.entrypoints=web"
      - "traefik.http.routers.bitwarden.middlewares=secHeaders@file,bitwarden-redirect@docker"
      - "traefik.http.middlewares.bitwarden-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.bitwarden-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.bitwarden-sec-header.headers.framedeny=true"
      - "traefik.http.middlewares.bitwarden-sec-header.headers.sslredirect=true"
      - "traefik.http.routers.bitwarden-secured.rule=Host(`bitwarden.domain.de`)"
      - "traefik.http.routers.bitwarden-secured.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-secured.tls=true"
      - "traefik.http.routers.bitwarden-secured.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitwarden-secured.middlewares=secHeaders@file"
      - "traefik.http.routers.bitwarden-secured.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=8080"
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true
    name: traefik-net
```
6. run `sed -i 's/public/traefik-net/g' docker-compose.yml`
7. remove port under service bitwarden-nginx and remove network public
8. run bitwarden.sh start

### Expected Result

working  Bitwarden

### Actual Result

502 Bad Gateway nginx

nginx error.log:
```
2023/01/29 12:49:59 [error] 48#48: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.3, server: bitwarden.domain.de, request: "GET / HTTP/1.1", upstream: "http://172.23.0.4:5000/", host: "bitwarden.domain.de"
```

### Additional Context

I have noticed that the default.conf from Nginx does not match the container names. The container is called "web" in the Nginx default.conf, but "bitwarden-web" in the docker-compose.yml. This applies to all containers in the default.conf, as the "bitwarden-" prefix is missing before the container names everywhere.

docker-compose.yml from traefik 2.9
```
version: '3.8'
services:
  traefik:
    image: traefik:2.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./dynamic.yaml:/etc/traefik/dynamic.yaml"
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-net"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=<Mail>"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true
    name: traefik-net
```
dynamic.yaml (for traefik 2.9)
```
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15768000
```

### Build Version

2023.1.0

### Environment

Self-Hosted

### Environment Details

- Operating system: [Ubuntu 20.04]
- Environment: [Docker]
- Docker version: [20.10.23]
- Docker compose version: [1.29.2]
- Hardware: [4 vCPUs, 16GB RAM]

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.
