### ISSUE TITLE
Unable to start after fresh install

### ISSUE THREAD

**Issue by SoftwareSchlosser** [bitwarden/server#2839]
### Steps To Reproduce

1. Install bitwarden following the steps from [install instructions](https://bitwarden.com/help/install-on-premise-linux/)
2. only edit smtp variables in env/global.override.env
3. run ./bitwarden.sh start

### Expected Result

Bitwarden docker container starts.

### Actual Result

This is the output of _./bitwarden.sh start_:

```
 ./bitwarden.sh start
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2023, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2023.3.0
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
docker-compose version 1.29.2, build unknown

Pulling mssql         ... done
Pulling web           ... done
Pulling attachments   ... done
Pulling api           ... done
Pulling identity      ... done
Pulling sso           ... done
Pulling admin         ... done
Pulling icons         ... done
Pulling notifications ... done
Pulling events        ... done
Pulling nginx         ... done
Creating directory /opt/bitwarden/bwdata/core
Creating directory /opt/bitwarden/bwdata/core/attachments
Creating directory /opt/bitwarden/bwdata/logs
Creating directory /opt/bitwarden/bwdata/logs/admin
Creating directory /opt/bitwarden/bwdata/logs/api
Creating directory /opt/bitwarden/bwdata/logs/events
Creating directory /opt/bitwarden/bwdata/logs/icons
Creating directory /opt/bitwarden/bwdata/logs/identity
Creating directory /opt/bitwarden/bwdata/logs/mssql
Creating directory /opt/bitwarden/bwdata/logs/nginx
Creating directory /opt/bitwarden/bwdata/logs/notifications
Creating directory /opt/bitwarden/bwdata/logs/sso
Creating directory /opt/bitwarden/bwdata/logs/portal
Creating directory /opt/bitwarden/bwdata/mssql/backups
Creating directory /opt/bitwarden/bwdata/mssql/data
ERROR: Network "docker_default" needs to be recreated - internal has changed
```

Output of _docker network inspect docker_default_

```
[
    {
        "Name": "docker_default",
        "Id": ".....",
        "Created": "2023-04-06T11:50:26.405821134+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.30.0.0/16",
                    "Gateway": "172.30.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "docker",
            "com.docker.compose.version": "1.29.2"
        }
    }
]
```

### Githash Version

can't retrieve

### Environment Details

- (L)Ubuntu 22.04.2 LTS
- Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello There, 

We use GitHub issues as a place to track bugs and other development related issues. 

Please write us using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

**Comment by SoftwareSchlosser** [comment]
Create/edit the file _bwdata/docker/docker-compose.override.yml_:

```
services:
  mssql:
    networks:
      - bitwarden
  web:
    networks:
      - bitwarden
  attachments:
    networks:
      - bitwarden
  api:
    networks:
      - bitwarden
  identity:
    networks:
      - bitwarden
  admin:
    networks:
      - bitwarden
  icons:
    networks:
      - bitwarden
  notifications:
    networks:
      - bitwarden
  nginx:
    networks:
      - bitwarden

networks:
  bitwarden:
    internal: true
  default:
    internal: false
```

You're welcome.

**Comment by SoftwareSchlosser** [comment]
Create or edit the file _bwdata/docker/docker-compose.override.yml_:

```
services:
  mssql:
    networks: [ bitwarden ]
  web:
    networks: [ bitwarden ]
  attachments:
    networks: [ bitwarden ]
  api:
    networks: [ bitwarden, public ]
  identity:
    networks: [ bitwarden, public ]
  sso:
    networks: [ bitwarden, public ]
  admin:
    networks: [ bitwarden, public ]
  icons:
    networks: [ bitwarden, public ]
  notifications:
    networks: [ bitwarden, public ]
  events:
    networks: [ bitwarden, public ]
  nginx:
    networks: [ bitwarden, public ]

networks:
  bitwarden:
    internal: true
  default:
    internal: false
```

You're welcome.
