### ISSUE TITLE
Image broken? Unable to create account

### ISSUE THREAD

**Issue by bermudi** [bitwarden/server#2997]
### Steps To Reproduce

1. Follow steps here 'https://bitwarden.com/help/install-and-deploy-unified-beta/#reporting-issues'
2. Go to BW_DOMAIN
3. Click on small 'New around here? Create account' link on Login Page
4. Fill out details
5. Click on 'Create account' button

### Expected Result

Create the account and enter admin area

### Actual Result

Nothing actually happens. Neither Chrome nor Firefox seem to log any kind of request being made in the Network tab.

Password hint and trying to log in seem to generate requests captured in the Network tab.

### Screenshots or Videos

![image](https://github.com/bitwarden/server/assets/9709492/5184ee54-a5be-40bc-95ea-f50e9bd424d7)
![image](https://github.com/bitwarden/server/assets/9709492/540ea680-7d30-4217-991d-42c33b3e041a)

### Additional Context

```
bermudi@server:~/docker/bitwarden$ cat settings.env 
# Server hostname
BW_DOMAIN=bermudi.dev

# Database
# Available providers are sqlserver, postgresql, mysql/mariadb, or sqlite
BW_DB_PROVIDER=mysql
BW_DB_SERVER=db
BW_DB_DATABASE=bitwarden_vault
BW_DB_USERNAME=bitwarden
BW_DB_PASSWORD=super_strong_password

# Installation information
# Get your ID and key from https://bitwarden.com/host/
BW_INSTALLATION_ID=ada25806-....-.....-.....-....................
BW_INSTALLATION_KEY=Tatzy.............

```

````
bermudi@server:~/docker/bitwarden$ cat docker-compose.yml 
---
version: "3.8"

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - settings.env
    image: bitwarden/self-host:beta
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden

  # MariaDB Example
  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

volumes:
  bitwarden:
  logs:
  data:
````

### Githash Version

"1202a670-dirty"

### Environment Details

- Ubuntu 22.04.2 LTS
- Docker version 24.0.2, build cb74dfc
-  6 vCPUs, 24 GB RAM, Disk 400GB

### Database Image

I tried mariadb:10 and sqlite

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.
