### ISSUE TITLE
gave up: nginx entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by nexcode** [bitwarden/server#3258]
### Steps To Reproduce

Make a config in which nginx starts on 80 and 443 ports:

```yml
version: "3.9"
services:
  bitwarden:
    image: bitwarden/self-host:2023.8.2-beta
    container_name: bitwarden
    hostname: wallet.nexcode.pro
    environment:
      BW_PORT_HTTP: 80
      BW_PORT_HTTPS: 443
```

### Expected Result

Normal nginx startup!

### Actual Result

```text
bitwarden  | 2023-09-09 12:22:24,452 INFO supervisord started with pid 1
bitwarden  | 2023-09-09 12:22:25,456 INFO spawned: 'identity' with pid 74
bitwarden  | 2023-09-09 12:22:25,463 INFO spawned: 'admin' with pid 75
bitwarden  | 2023-09-09 12:22:25,476 INFO spawned: 'api' with pid 76
bitwarden  | 2023-09-09 12:22:25,485 INFO spawned: 'icons' with pid 77
bitwarden  | 2023-09-09 12:22:25,502 INFO spawned: 'nginx' with pid 78
bitwarden  | 2023-09-09 12:22:25,517 INFO spawned: 'notifications' with pid 79
bitwarden  | 2023-09-09 12:22:26,631 INFO exited: nginx (exit status 1; not expected)
bitwarden  | 2023-09-09 12:22:27,633 INFO spawned: 'nginx' with pid 117
bitwarden  | 2023-09-09 12:22:27,810 INFO exited: nginx (exit status 1; not expected)
bitwarden  | 2023-09-09 12:22:30,263 INFO spawned: 'nginx' with pid 139
bitwarden  | 2023-09-09 12:22:31,346 INFO exited: nginx (exit status 1; not expected)
bitwarden  | 2023-09-09 12:22:34,673 INFO spawned: 'nginx' with pid 152
bitwarden  | 2023-09-09 12:22:35,701 INFO exited: nginx (exit status 1; not expected)
bitwarden  | 2023-09-09 12:22:36,703 INFO gave up: nginx entered FATAL state, too many start retries too quickly
```

### Githash Version

doesn't work because nginx didn't start

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.
