### ISSUE TITLE
Error when already using a docker-compose.yml

### ISSUE THREAD

**Issue by markisoke** [bitwarden/server#372]
I already have some applications running with an existing docker-compose.yml, when I want to install Bitwarden I get the following error during ./bitwarden.sh start

WARNING: Found orphan containers (xxxxxxx, xxxxxxxx, xxxxxxxx, xxxxxxxx, xxxxxxx) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing network docker_default
ERROR: network docker_default id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx has active endpoints

Of course, these are active containers and not orphan ones. How can I still install Bitwarden?

**Comment by all3kcis** [comment]
Maybe you can try that :
In `bwdata/docker` create file `docker-compose.override.yml`

```
version: '3'

services:
  mssql:
    networks:
      - netbit

  web:
    networks:
      - netbit

  attachments:
    networks:
      - netbit

  api:
    networks:
      - netbit

  identity:
    networks:
      - netbit

  admin:
    networks:
      - netbit

  icons:
    networks:
      - netbit

  notifications:
    networks:
      - netbit

  nginx:
    networks:
      - netbit

networks:
  netbit:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
    driver_opts:
      com.docker.network.bridge.name: dockerbitwarden
```
