### ISSUE TITLE
Bitwarden nginx 502 + jwilder/nginx-proxy

### ISSUE THREAD

**Issue by Jerome2103** [bitwarden/server#549]
Hello everybody

I need help.
I have set up bitwarden, and now comes a 502 error.

Do not see the mistake, have already tried different.

Thanks in advance.

config.yml
```# 
# Note: After making changes to this file you need to run the `rebuild` or `update`
# command for them to be applied.
# 
# Full URL for accessing the installation from a browser. (Required)
url: https://host.xyz
# 
# Auto-generate the `./docker/docker-compose.yml` config file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/DockerCompose.hbs
generate_compose_config: true
# 
# Auto-generate the `./nginx/default.conf` file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/NginxConfig.hbs
generate_nginx_config: true
# 
# Docker compose file port mapping for HTTP. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
http_port: 8000
```

And here the docker-compose.override.yml file:
docker-compose.override.yml
```
version: '3'
services:
 nginx:
    ports:
      - 8000
    environment:
      - VIRTUAL_HOST=host.xyz
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=host.xyz
      - LETSENCRYPT_EMAIL=email
    networks:
      webproxy:

networks:
  webproxy:
    external:
      name: nginx-proxy
```

**Comment by crafti5** [comment]
check the settings in nginx conf, which is generated. 
I got an error here where the listen port was 8080 but not the configured http_port 8000.

You can get around this with following:

`version: '3'
services:
 nginx:
    ports:
      - 8080
    environment:
      - VIRTUAL_HOST=host.xyz
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=host.xyz
      - LETSENCRYPT_EMAIL=email
    networks:
      webproxy:

networks:
  webproxy:
    external:
      name: nginx-proxy`

**Comment by Pulsar** [comment]
Bitwarden nginx requires **https** connection, the right port in your case is **8443** and your configuration should look like this:

```yaml
  environment:
    # Reverse proxy variables
    - VIRTUAL_HOST=host.xyz
    - VIRTUAL_PORT=8443
    - VIRTUAL_PROTO=https
    # Letsencrypt variables
    - LETSENCRYPT_HOST=host.xyz
    - LETSENCRYPT_EMAIL=admin@host.xyz
```

In my case the (working) configuration looks like this:
```yaml
nginx:
  container_name: bitwarden-nginx
  image: bitwarden/nginx:${BITWARDEN_VERSION}-build
  build:
    context: ./nginx
    dockerfile: Dockerfile
    args:
      nginx_version: 1.16
  restart: unless-stopped
  environment:
    # Reverse proxy variables
    - VIRTUAL_HOST=bitwarden.${BASE_DOMAIN}
    - VIRTUAL_PORT=8443
    - VIRTUAL_PROTO=https
    # Letsencrypt variables
    - LETSENCRYPT_HOST=bitwarden.${BASE_DOMAIN}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    # Bitwarden
    - BW_UID=1000
    - BW_GID=1000
    - BW_HOST=bitwarden.${BASE_DOMAIN}
    - BW_TLS_PATH=/etc/certs
  volumes:
    - certs-volume:/etc/certs # certificates
    - ${BASE_DIR}/bitwarden/logs/nginx:/var/log/nginx
  networks:
    proxy-net:
      aliases:
        - bitwarden.${BASE_DOMAIN}
    bitwarden-net:
  depends_on:
    - web
    - admin
    - api
    - identity
```


Please consider closing the issue if your problem gets resolved.
