### ISSUE TITLE
 Docker Interface overlap with Local LAN

### ISSUE THREAD

**Issue by mrventerj** [bitwarden/server#947]
My LAN is 172.28.0.0\16 and its route should be 10.3.0.1

It seems that the docker is conflicting with the LAN - can and how do I change the subnet for docker?

Kernel IP routing table
Destination Gateway Genmask Flags MSS Window irtt Iface
0.0.0.0 10.3.0.1 0.0.0.0 UG 0 0 0 eth0
10.3.0.0 0.0.0.0 255.255.255.0 U 0 0 0 eth0
168.63.129.16 10.3.0.1 255.255.255.255 UGH 0 0 0 eth0
169.254.169.254 10.3.0.1 255.255.255.255 UGH 0 0 0 eth0
172.17.0.0 0.0.0.0 255.255.0.0 U 0 0 0 docker0
172.28.0.0 0.0.0.0 255.255.0.0 U 0 0 0 br-828c78b615e2
172.29.0.0 0.0.0.0 255.255.0.0 U 0 0 0 br-adff3a5cad70

**Comment by pgumeniuk** [comment]
It's quite easy. Just add ipam settings to your compose file:
```
networks:
  default:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"
  public:
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "172.18.2.0/24"
```
